export const projectsData = [
  {
    id: "1",
    title: "Quizzical",
    description:
      "A React Trivia App quizzing users on books. React Hooks were used to bring quiz data from a Trivia API, then modified and used in React Components to display questions, options, user’s choices, and final score with right / wrong answers highlighted. Used Figma design file provided to build the app.",
    imageUrl: "",
    githubUrl: "https://github.com/soojeong-park-ca/quizzical",
    liveSiteUrl: "https://quizzical-spark.netlify.app/",
    tools: [
      "HTML5",
      "CSS3",
      "React",
      "API",
      "Vite",
      "Responsive",
      "Mobile-first",
    ],
  },
  {
    id: "2",
    title: "Natours",
    description:
      "A landing page for a fictional tour company called “Natours.” The website includes different sections: About, Features, Plans, Testimonial, Sign-up Form.",
    imageUrl: "",
    githubUrl: "https://github.com/soojeong-park-ca/quizzical",
    liveSiteUrl: "https://quizzical-spark.netlify.app/",
    tools: ["HTML5", "SASS(SCSS)", "JavaScript", "Responsive"],
  },
  {
    id: "3",
    title: "Vanlife",
    description: "Currently building this app",
    imageUrl: "",
    githubUrl: "",
    liveSiteUrl: "",
    tools: [
      "HTML5",
      "CSS Modules",
      "React",
      "React Router 6",
      "Vite",
      "Responsive",
      "Mobile-first",
    ],
  },
  {
    id: "4",
    title: "Soojeong Park Portfolio Website",
    description: "Currently building this app",
    imageUrl: "",
    githubUrl: "",
    liveSiteUrl: "",
    tools: [
      "HTML5",
      "SASS(SCSS)",
      "React",
      "React Router 6",
      "Vite",
      "Responsive",
      "Mobile-first",
    ],
  },
];
